# Generated by Django 4.2.2 on 2023-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=220)),
                ('lname', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=220)),
                ('checkbox', models.BooleanField()),
            ],
        ),
    ]
