# Generated by Django 4.2.2 on 2023-06-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0002_signuppatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=220)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood', models.CharField(max_length=220)),
                ('medhistory', models.CharField(max_length=1000)),
                ('meddetails', models.CharField(max_length=1000)),
                ('healthcond', models.CharField(max_length=1000)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('?', 'Prefer not to say')], max_length=1)),
                ('presimage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
