# Generated by Django 4.2.2 on 2023-06-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0003_patientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='presimage',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
