# Generated by Django 4.2.2 on 2023-06-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prescription', '0004_alter_patientdetails_presimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='gender',
        ),
    ]
